
# Available substitutions:
# * `$DISPLAY_NAME`
# * `$BINARY`
# * `$FLAGS`
# * `$COMMAND`
terminal = "alacritty --title $DISPLAY_NAME --command $COMMAND"

language = "en"


# Available default plugins:
# * `"xdg"`
# * `"path"`
plugins = ["xdg", "path"]

# Available dynamic plugin kinds:
# * `"dummy"`
[[plugin]]
kind = "dummy"

[[plugin]]
kind = 'lua'
file = 'assets/steam.lua'

[[plugin]]
kind = 'lua'
file = 'assets/roms.lua'

[ui.terminal]
enable=true

[ui.graphical]
enable=true
default=true 